#include "NodeScribePropertyText.h"

#include "AnimGraphNode_Base.h"
#include "Animation/AnimNodeBase.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Misc/StringOutputDevice.h"
#include "UObject/EnumProperty.h"
#include "UObject/TextProperty.h"
#include "UObject/UnrealType.h"

namespace NodeScribePropertyText
{

// -- Quotes ------------------------------------------------------------------

bool NeedsQuotes(const FString& Value)
{
	if (Value.IsEmpty())
	{
		return true;
	}

	// An asset path is read raw by the builder and has no separator inside.
	if (Value.StartsWith(TEXT("/")) && !Value.Contains(TEXT(" ")))
	{
		return false;
	}

	if (Value.StartsWith(TEXT("$")))
	{
		return true;
	}

	for (const TCHAR C : Value)
	{
		if (C == TEXT(' ') || C == TEXT(',') || C == TEXT('(') || C == TEXT(')')
			|| C == TEXT('#') || C == TEXT('=') || C == TEXT('"') || C == TEXT('\''))
		{
			return true;
		}
	}

	return Value.Contains(TEXT("//"));
}

bool TryQuote(const FString& Value, FString& OutQuoted)
{
	const bool bHasDouble = Value.Contains(TEXT("\""));
	const bool bHasSingle = Value.Contains(TEXT("'"));

	if (bHasDouble && bHasSingle)
	{
		return false;
	}

	const TCHAR* Quote = bHasDouble ? TEXT("'") : TEXT("\"");
	OutQuoted = Quote + Value + Quote;
	return true;
}

namespace
{
	/** Quotes only when the line needs it. */
	bool QuoteIfNeeded(const FString& Value, FString& OutText)
	{
		if (!NeedsQuotes(Value))
		{
			OutText = Value;
			return true;
		}
		return TryQuote(Value, OutText);
	}

	/** Strips the quotes QuoteIfNeeded adds. Without quotes, returns it as it came. */
	FString Unquote(const FString& Text)
	{
		if (Text.Len() >= 2)
		{
			const TCHAR First = Text[0];
			if ((First == TEXT('"') || First == TEXT('\'')) && Text[Text.Len() - 1] == First)
			{
				return Text.Mid(1, Text.Len() - 2);
			}
		}
		return Text;
	}

	/** The enum as it shows on screen, without the type prefix. */
	bool EnumValueToText(const UEnum* Enum, int64 Value, FString& OutText)
	{
		const int32 Index = Enum->GetIndexByValue(Value);
		if (Index == INDEX_NONE)
		{
			return false;
		}
		// GetNameStringByIndex drops the `EPlayerMappableKeySlot::` and leaves `First`.
		OutText = Enum->GetNameStringByIndex(Index);
		return !OutText.IsEmpty();
	}

	bool TextToEnumValue(const UEnum* Enum, const FString& Text, int64& OutValue)
	{
		int64 Value = Enum->GetValueByNameString(Text);
		if (Value == INDEX_NONE)
		{
			// Also accepts the qualified name, which is what the Engine's
			// ExportText produces -- so text coming from outside the plugin still
			// goes in.
			Value = Enum->GetValueByNameString(Enum->GenerateFullEnumName(*Text));
		}
		if (Value == INDEX_NONE)
		{
			return false;
		}
		OutValue = Value;
		return true;
	}
}

// -- Names -------------------------------------------------------------------

FString FormatFloat(double Value)
{
	return FString::SanitizeFloat(Value);
}

FString DescribePinType(const FEdGraphPinType& PinType)
{
	FString Base;

	const FName Category = PinType.PinCategory;
	UObject* SubCategory = PinType.PinSubCategoryObject.Get();

	if (Category == UEdGraphSchema_K2::PC_Boolean)      { Base = TEXT("Boolean"); }
	else if (Category == UEdGraphSchema_K2::PC_Int)     { Base = TEXT("Integer"); }
	else if (Category == UEdGraphSchema_K2::PC_Int64)   { Base = TEXT("Int64"); }
	else if (Category == UEdGraphSchema_K2::PC_Real)    { Base = TEXT("Float"); }
	else if (Category == UEdGraphSchema_K2::PC_String)  { Base = TEXT("String"); }
	else if (Category == UEdGraphSchema_K2::PC_Name)    { Base = TEXT("Name"); }
	else if (Category == UEdGraphSchema_K2::PC_Text)    { Base = TEXT("Text"); }
	else if (Category == UEdGraphSchema_K2::PC_Byte)
	{
		// Enum and byte share a category; the object is what tells them apart.
		Base = SubCategory ? SubCategory->GetName() : TEXT("Byte");
	}
	else if (SubCategory)
	{
		Base = SubCategory->GetName();

		// `BP_Golem_C` is the name of the class generated by compilation. Nobody
		// types that suffix, it shows up nowhere in the interface, and the class
		// lookup accepts both forms -- writing `BP_Golem_C` on the way back would
		// only teach a second name for the same thing.
		Base.RemoveFromEnd(TEXT("_C"));

		// A reference to the class, not the instance. Without the suffix, the
		// text read comes back as an object reference -- a `BP_Rock Class`
		// variable would become `BP_Rock`, and the Spawn Actor node would stop
		// accepting it.
		if (Category == UEdGraphSchema_K2::PC_Class
			|| Category == UEdGraphSchema_K2::PC_SoftClass)
		{
			Base += TEXT(" Class");
		}
	}
	else
	{
		return FString();
	}

	switch (PinType.ContainerType)
	{
	case EPinContainerType::Array:
		return TEXT("Array of ") + Base;

	case EPinContainerType::Set:
		return TEXT("Set of ") + Base;

	case EPinContainerType::Map:
	{
		// Without this a `TMap<int64, BP_Mirror>` came out as `Int64`: the fact
		// that it is a map vanishes, and so does the value type. The reader
		// understands "an int64 variable", and pasting that line back creates
		// exactly that -- a variable of another type, with no warning at all.
		const FString ValueName = DescribePinType(
			FEdGraphPinType::GetPinTypeForTerminalType(PinType.PinValueType));

		// `?` in place of the type we could not name: the builder refuses the
		// line and says which one. Better than returning empty, which would make
		// the whole variable vanish.
		return FString::Printf(TEXT("Map of %s to %s"),
			*Base, ValueName.IsEmpty() ? TEXT("?") : *ValueName);
	}

	default:
		return Base;
	}
}

FString DescribeType(const FProperty* Property)
{
	if (!Property)
	{
		return FString();
	}

	// Going through the pin type is deliberate: it guarantees the sheet and the
	// graph call the same type by the same name, without having to remember to
	// change both when one of them changes.
	//
	// GetDefault, not construction on the stack: a UObject class cannot be
	// instantiated that way -- the constructor calls FObjectInitializer::Get(),
	// which is only valid inside a UObject constructor, and brings the editor
	// down on the spot. This already brought the editor down once (cac90d8); it
	// compiles without complaint.
	FEdGraphPinType PinType;
	if (!GetDefault<UEdGraphSchema_K2>()->ConvertPropertyToPinType(Property, PinType))
	{
		return FString();
	}

	return DescribePinType(PinType);
}

FString DisplayName(const FProperty* Property)
{
	if (!Property)
	{
		return FString();
	}

	const FString Display = Property->GetDisplayNameText().ToString();
	return Display.IsEmpty() ? Property->GetName() : Display;
}

// -- Pins --------------------------------------------------------------------

bool IsExecPin(const UEdGraphPin* Pin)
{
	return Pin && Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec;
}

bool IsObjectLikePin(const UEdGraphPin* Pin)
{
	if (!Pin)
	{
		return false;
	}

	const FName Category = Pin->PinType.PinCategory;
	return Category == UEdGraphSchema_K2::PC_Object
		|| Category == UEdGraphSchema_K2::PC_Class
		|| Category == UEdGraphSchema_K2::PC_SoftObject
		|| Category == UEdGraphSchema_K2::PC_SoftClass
		|| Category == UEdGraphSchema_K2::PC_Interface;
}

// -- Visibility --------------------------------------------------------------

bool IsVisible(const FProperty* Property)
{
	if (!Property)
	{
		return false;
	}

	if (Property->HasAnyPropertyFlags(CPF_Transient | CPF_Deprecated))
	{
		return false;
	}

	return Property->HasAnyPropertyFlags(CPF_Edit | CPF_BlueprintVisible);
}

// -- Node options ------------------------------------------------------------

bool IsNodeSetting(const FProperty* Property)
{
	if (!Property)
	{
		return false;
	}

	if (!Property->HasAnyPropertyFlags(CPF_Edit)
		|| Property->HasAnyPropertyFlags(CPF_EditConst | CPF_Transient | CPF_Deprecated))
	{
		return false;
	}

	// What `UEdGraphNode` declares is editor plumbing: position, size, comment,
	// guid. None of that says what the node does, and the guid on top of that
	// differs on every node -- so it would come out on every line.
	//
	// `UAnimGraphNode_Base` is the same thing one floor up: `Binding` and
	// `Show Pin for Properties` decide which fields become pins and how the node
	// draws itself. The real configuration of an anim node lives in the
	// `FAnimNode_*` struct it carries, and that is where `Loop Animation` comes
	// from. Without this line, every asset player read came out with a
	// `Binding = /Game/.../AnimGraphNodeBinding_Base_0` -- a subobject path that
	// does not come back on pasting -- and a warning that `Show Pin for
	// Properties` changed and does not fit in text, on every node of the graph.
	if (Property->GetOwnerClass() == UEdGraphNode::StaticClass()
		|| Property->GetOwnerClass() == UAnimGraphNode_Base::StaticClass())
	{
		return false;
	}

	// An instanced subobject does not come back through text: the value is a
	// path to an object that only exists inside this node.
	if (Property->HasAnyPropertyFlags(CPF_InstancedReference))
	{
		return false;
	}

	return true;
}

bool IsAnimNodeStruct(const FStructProperty* Property)
{
	return Property && Property->Struct
		&& Property->Struct->IsChildOf(FAnimNode_Base::StaticStruct());
}

// -- Value -------------------------------------------------------------------

bool ValueToText(const FProperty* Property, const void* ValuePtr, FString& OutText)
{
	if (!Property || !ValuePtr)
	{
		return false;
	}

	// Bool first: FBoolProperty is also numeric inside, and would fall into the
	// number branch as `1` instead of `true`.
	if (const FBoolProperty* BoolProperty = CastField<FBoolProperty>(Property))
	{
		OutText = BoolProperty->GetPropertyValue(ValuePtr) ? TEXT("true") : TEXT("false");
		return true;
	}

	// Enum before number for the same reason: inside it is a byte.
	if (const FEnumProperty* EnumProperty = CastField<FEnumProperty>(Property))
	{
		const FNumericProperty* Underlying = EnumProperty->GetUnderlyingProperty();
		const int64 Value = Underlying->GetSignedIntPropertyValue(ValuePtr);
		if (EnumValueToText(EnumProperty->GetEnum(), Value, OutText))
		{
			return true;
		}
		// A value outside the enum happens with old data. The raw number comes
		// back the same, so stating the number is better than refusing the line.
		OutText = LexToString(Value);
		return true;
	}

	if (const FByteProperty* ByteProperty = CastField<FByteProperty>(Property))
	{
		const int64 Value = ByteProperty->GetSignedIntPropertyValue(ValuePtr);
		if (ByteProperty->Enum && EnumValueToText(ByteProperty->Enum, Value, OutText))
		{
			return true;
		}
		OutText = LexToString(Value);
		return true;
	}

	if (const FNumericProperty* NumericProperty = CastField<FNumericProperty>(Property))
	{
		if (NumericProperty->IsFloatingPoint())
		{
			OutText = FormatFloat(NumericProperty->GetFloatingPointPropertyValue(ValuePtr));
		}
		else
		{
			OutText = LexToString(NumericProperty->GetSignedIntPropertyValue(ValuePtr));
		}
		return true;
	}

	if (const FStrProperty* StrProperty = CastField<FStrProperty>(Property))
	{
		return QuoteIfNeeded(StrProperty->GetPropertyValue(ValuePtr), OutText);
	}

	if (const FNameProperty* NameProperty = CastField<FNameProperty>(Property))
	{
		return QuoteIfNeeded(NameProperty->GetPropertyValue(ValuePtr).ToString(), OutText);
	}

	if (const FTextProperty* TextProperty = CastField<FTextProperty>(Property))
	{
		return QuoteIfNeeded(TextProperty->GetPropertyValue(ValuePtr).ToString(), OutText);
	}

	// An asset reference comes out as a full path, same as the graph. A bare
	// name would be shorter and ambiguous -- two folders may have `SKM_Golem`,
	// and choosing the wrong one is the mistake this plugin refuses to make.
	if (const FObjectPropertyBase* ObjectProperty = CastField<FObjectPropertyBase>(Property))
	{
		const UObject* Value = ObjectProperty->LoadObjectPropertyValue(ValuePtr);
		OutText = Value ? Value->GetPathName() : TEXT("None");
		return true;
	}

	if (const FSoftObjectProperty* SoftProperty = CastField<FSoftObjectProperty>(Property))
	{
		const FSoftObjectPtr& Value = SoftProperty->GetPropertyValue(ValuePtr);
		OutText = Value.IsNull() ? TEXT("None") : Value.ToString();
		return true;
	}

	// Struct, array, map and set come out whole in the Engine's canonical form.
	// Recursing inside would look nicer and open a class of round-trip error
	// that does not exist today; it waits until the sheet has more mileage.
	FString Exported;
	Property->ExportTextItem_Direct(Exported, ValuePtr, nullptr, nullptr, PPF_None);
	if (Exported.IsEmpty())
	{
		return false;
	}

	return QuoteIfNeeded(Exported, OutText);
}

bool TextToValue(const FProperty* Property, void* ValuePtr, const FString& Text, FString& OutError)
{
	if (!Property || !ValuePtr)
	{
		OutError = TEXT("null property or destination");
		return false;
	}

	const FString Bare = Unquote(Text).TrimStartAndEnd();

	if (const FBoolProperty* BoolProperty = CastField<FBoolProperty>(Property))
	{
		if (Bare.Equals(TEXT("true"), ESearchCase::IgnoreCase))
		{
			BoolProperty->SetPropertyValue(ValuePtr, true);
			return true;
		}
		if (Bare.Equals(TEXT("false"), ESearchCase::IgnoreCase))
		{
			BoolProperty->SetPropertyValue(ValuePtr, false);
			return true;
		}
		OutError = FString::Printf(TEXT("`%s` is neither true nor false"), *Bare);
		return false;
	}

	if (const FEnumProperty* EnumProperty = CastField<FEnumProperty>(Property))
	{
		const UEnum* Enum = EnumProperty->GetEnum();
		int64 Value = 0;
		if (!Enum || !TextToEnumValue(Enum, Bare, Value))
		{
			OutError = FString::Printf(TEXT("`%s` is not a value of %s"),
				*Bare, Enum ? *Enum->GetName() : TEXT("enum"));
			return false;
		}
		EnumProperty->GetUnderlyingProperty()->SetIntPropertyValue(ValuePtr, Value);
		return true;
	}

	if (const FByteProperty* ByteProperty = CastField<FByteProperty>(Property))
	{
		if (ByteProperty->Enum)
		{
			int64 Value = 0;
			if (TextToEnumValue(ByteProperty->Enum, Bare, Value))
			{
				ByteProperty->SetIntPropertyValue(ValuePtr, Value);
				return true;
			}
		}
		// No enum, or a name that does not match: falls into the number, below.
	}

	if (const FNumericProperty* NumericProperty = CastField<FNumericProperty>(Property))
	{
		if (NumericProperty->IsFloatingPoint())
		{
			if (!Bare.IsNumeric())
			{
				OutError = FString::Printf(TEXT("`%s` is not a number"), *Bare);
				return false;
			}
			NumericProperty->SetFloatingPointPropertyValue(ValuePtr, FCString::Atod(*Bare));
			return true;
		}

		if (!Bare.IsNumeric())
		{
			OutError = FString::Printf(TEXT("`%s` is not an integer"), *Bare);
			return false;
		}
		NumericProperty->SetIntPropertyValue(ValuePtr, static_cast<int64>(FCString::Atoi64(*Bare)));
		return true;
	}

	if (const FStrProperty* StrProperty = CastField<FStrProperty>(Property))
	{
		StrProperty->SetPropertyValue(ValuePtr, Bare);
		return true;
	}

	if (const FNameProperty* NameProperty = CastField<FNameProperty>(Property))
	{
		NameProperty->SetPropertyValue(ValuePtr, FName(*Bare));
		return true;
	}

	if (const FTextProperty* TextProperty = CastField<FTextProperty>(Property))
	{
		TextProperty->SetPropertyValue(ValuePtr, FText::FromString(Bare));
		return true;
	}

	if (const FObjectPropertyBase* ObjectProperty = CastField<FObjectPropertyBase>(Property))
	{
		if (Bare.Equals(TEXT("None"), ESearchCase::IgnoreCase))
		{
			ObjectProperty->SetObjectPropertyValue(ValuePtr, nullptr);
			return true;
		}

		// Paths only. A bare name that is not a path is not accepted -- the same
		// rule as the graph, and for the same reason: guessing which asset it was
		// produces a plausible, wrong value.
		if (!Bare.StartsWith(TEXT("/")))
		{
			OutError = FString::Printf(
				TEXT("`%s` is not an asset path; use the full path"), *Bare);
			return false;
		}

		UObject* Loaded = StaticLoadObject(ObjectProperty->PropertyClass, nullptr, *Bare);
		if (!Loaded)
		{
			OutError = FString::Printf(TEXT("could not find `%s`"), *Bare);
			return false;
		}
		ObjectProperty->SetObjectPropertyValue(ValuePtr, Loaded);
		return true;
	}

	// Struct, array, map and set come back through the Engine's canonical form,
	// which is exactly what ValueToText emitted for them.
	FStringOutputDevice ImportError;
	const TCHAR* Result = Property->ImportText_Direct(*Bare, ValuePtr, nullptr, PPF_None, &ImportError);
	if (!Result || !ImportError.IsEmpty())
	{
		OutError = ImportError.IsEmpty()
			? FString::Printf(TEXT("`%s` does not fit into %s"), *Bare, *Property->GetName())
			: FString(ImportError).TrimStartAndEnd();
		return false;
	}

	return true;
}

bool DiffersFromDefault(const FProperty* Property, const void* ValuePtr, const void* DefaultPtr)
{
	if (!Property || !ValuePtr)
	{
		return false;
	}

	// Without an archetype there is nothing to compare with, and saying "did
	// not change" would hide everything. In that case every property is news.
	if (!DefaultPtr)
	{
		return true;
	}

	// An own component does not count as a change.
	//
	// BP_Golem's `Mesh` and Character's `Mesh` point at different objects --
	// each class has its own instance -- so the pointer always differs and a raw
	// comparison would mark every component as changed. In a sheet that is pure
	// noise, and noise on the longest lines: a subobject's path is huge and says
	// nothing. The details panel does not show those as overridden either.
	//
	// Same subobject name on both sides = it is the same component, seen from
	// two classes. Swapping the component for another changes the name, and
	// then it shows up.
	if (const FObjectPropertyBase* ObjectProperty = CastField<FObjectPropertyBase>(Property))
	{
		const UObject* Value = ObjectProperty->LoadObjectPropertyValue(ValuePtr);
		const UObject* Default = ObjectProperty->LoadObjectPropertyValue(DefaultPtr);

		if (Value && Default
			&& Value->IsDefaultSubobject() && Default->IsDefaultSubobject()
			&& Value->GetFName() == Default->GetFName())
		{
			return false;
		}
	}

	return !Property->Identical(ValuePtr, DefaultPtr, PPF_DeepComparison);
}

}
